In [1]:
from sklearn import datasets
boston=datasets.load_boston()

In [2]:
x=boston.data
y=boston.target
x.shape
y.shape

(506,)

In [3]:
import pandas as pd
df=pd.DataFrame(x)
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.593761,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.596783,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.647423,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [4]:
boston.feature_names
df.columns=boston.feature_names
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.593761,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.596783,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.647423,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [5]:
from sklearn import model_selection 
def split_data(x,y):
    return model_selection.train_test_split(x,y,random_state=1)
    
# print(x_train.shape)
# print(y_train.shape)
# print(x_test.shape)
# print(y_test.shape)

In [6]:
from sklearn.linear_model import LinearRegression
def fit_model(x,y):
    x_train,x_test,y_train,y_test=split_data(x,y)
    algo=LinearRegression()
    algo.fit(x_train,y_train)
    y_pred=algo.predict(x_test)
    test_score=algo.score(x_test,y_test)
    return test_score

In [7]:
print(fit_model(x,y))

0.779025774914

In [19]:
import numpy as np
a=np.array(x)
print(a.shape)
z=a[:,0]*a[:,0]
z=z.reshape(506,1)
a=np.append(a,z,axis=1)
print(z.shape)
print(a.shape)

(506, 13)
(506, 1)
(506, 14)

In [17]:
print(fit_model(a,y))

0.77885582941

In [23]:
a=np.array(x)
ll=list()
for i in range(14):
    for j in range(i,14):
        z=a[:,i]*a[:,j]
        z=z.reshape(506,1)
        a=np.append(a,z,axis=1)
        ll.append(fit_model(a,y))

In [26]:
ll

[0.7788558294103598,
 0.77782135489722737,
 0.77600284589490121,
 0.79088008253036368,
 0.79594788034952291,
 0.83323223122966072,
 0.8292157275720079,
 0.82785256613883473,
 0.82832908453356724,
 0.82792752745128861,
 0.82613200375224727,
 0.82126546986023063,
 0.82121816087721689,
 0.81630330521517536,
 0.81933221894861386,
 0.82070670942285906,
 0.82046256911678994,
 0.82136531377293365,
 0.82554508378383284,
 0.82532756994851375,
 0.82925284230981078,
 0.83042878297482281,
 0.83049079412827087,
 0.82620104466276212,
 0.82635207577908931,
 0.82691260955230761,
 0.82957557267704918,
 0.83073170579784006,
 0.82996857791204348,
 0.83080267206952818,
 0.84011517933741953,
 0.84174496241994967,
 0.84019338093230256,
 0.83476480443409928,
 0.84098831249483286,
 0.84070672973431948,
 0.83868813875948445,
 0.85375488750541906,
 0.85296450580335104,
 0.85296450580365457,
 0.85817827895968046,
 0.85485578540106877,
 0.85421524663368209,
 0.85415835193779277,
 0.85485758088154185,
 0.84868291654391947,
 0.8288241958676632,
 0.82919479522799011,
 0.82569011812271176,
 0.82966385742056026,
 0.82915729595977472,
 0.83069682640809162,
 0.83467313695101386,
 0.83795874103276602,
 0.83802434970099338,
 0.83906402914920586,
 0.84099920552580021,
 0.84300063715915896,
 0.84191446500225009,
 0.83142159215421652,
 0.86067933661213702,
 0.85169554402268033,
 0.85047976456277308,
 0.84885645518416453,
 0.84351950634051909,
 0.84861547509675861,
 0.84824635692210415,
 0.84858400258353839,
 0.84801802979403285,
 0.84896597921818007,
 0.84859565992237584,
 0.84596645730226061,
 0.83772376263232784,
 0.83690835689695731,
 0.85540400120045024,
 0.86981523098969904,
 0.8698166794844393,
 0.87237400217303418,
 0.87665656089934374,
 0.8788618148499302,
 0.87962611582425998,
 0.87911146052228828,
 0.88373464400145485,
 0.87688156761473135,
 0.87594317115154752,
 0.87871311719280132,
 0.87839055114174303,
 0.88014728130105035,
 0.90012291174683878,
 0.90022436405598527,
 0.89919330266491626,
 0.89454030833808984,
 0.89437266858746589,
 0.89182425091837503,
 0.89023816039862325,
 0.89139125081101522,
 0.89162862795691844,
 0.88731472758029706,
 0.88437716520659293,
 0.88593561630656747,
 0.88830091057103699,
 0.88346209997734471,
 0.87904010643266817,
 0.87786421090492461,
 0.87715400142757527]